# Generated by Django 2.2.4 on 2019-08-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_native', models.CharField(max_length=30, unique=True)),
                ('lang_english', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text_native', models.CharField(max_length=200)),
                ('lang_native', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.Language')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.Message')),
            ],
        ),
    ]
