# Generated by Django 2.2.4 on 2019-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_language_fill_lang_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_iso',
            field=models.CharField(default='en', max_length=2, unique=True),
        ),
    ]
