# Generated by Django 2.2.4 on 2019-09-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_language_lang_iso_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='text_translated',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('message', 'lang_target')},
        ),
    ]
