# Generated by Django 2.2.4 on 2019-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20190909_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_native',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_translated',
            field=models.TextField(),
        ),
    ]
