# Generated by Django 2.2.4 on 2019-09-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20190911_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Message'),
        ),
    ]
